version: "3.7"
volumes:
  client-node_modules:

services:

  # node apps
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: client
    environment:
      - COMMAND=${COMMAND:-start}
    env_file:
      - .env
    image: client
    ports:
      - 8080:3000
    volumes:
      - ./app:/app
      - client-node_modules:/app/node_modules
    tty: true
  